### ISSUE TITLE
Singleshot experiments compression and pruner settings

### ISSUE THREAD

**Issue by yaohuicai** [ganguli-lab/Synaptic-Flow#5]
Thank you for your wonderful paper and code released. It is very interesting to me.

I found the commands to run singleshot experiments in Synaptic-Flow/misc/Experiments_Figure_6.ipynb might have some problems. For example, the following command is used to run VGG-11 with SynFlow according to your annotations. 

`CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --optimizer=momentum --lr=0.1 --lr-drops 60 120 --lr-drop-rate=0.1 --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=0 --post-epochs=160 --gpu=0 --result-dir=/mnt/fs4/htanaka/SynFlow/Results --expid=0702_2020_cifar10_lottery_vgg11_bn_run0 --seed=0 --dataset=cifar10 --model-class=lottery --model=vgg11-bn --pruner-list synflow snip grasp rand mag --prune-epoch-list 100 1 1 1 1 --compression-list 3.0 2.75 2.5 2.25 2.0 1.75 1.5 1.25 1.0 0.75 0.5 0.25 0; `

Though `--compresion-list` and `--pruner-list` have been specified, they are useless in singleshot experiments. The `--compression` and `--pruner arguments` setting haven't been specified so these two settings will remain default as `--compression=0` and `--pruner=rand`. If I understand correctly, this command will do no pruning and simply train the full model for 160 epochs. I would love to know if I misunderstand anything.

Thanks!

**Comment by hidetana18** [comment]
Thank you for your comments.
We are actively updating our codebase after submitting the first version of our preprint, and the command from “Experiments_Figure_6.ipynb” in the miscellaneous folder is now outdated.
In particular we have made modifications so that we can spread trainings across multiple gpu.
We have now deleted “Experiments_Figure_6.ipynb” to avoid confusions.

To reproduce Fig. 6. with our current state of codebase, you could for example try a bash script (all the hyper parameters are in the appendix of our paper):

declare -a PrunerArray=("synflow" "snip" "grasp" "mag" "rand")
for seed in 0 1 2; do
    for val in "${PrunerArray[@]}"; do
        for d in 0.00 0.25 0.50 0.75 1.00 1.25 1.50 1.75 2.00 2.25 2.50 2.75 3.00; do
            if [ "$val" = "synflow" ]
            then
                CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --optimizer=momentum --lr=0.1 --lr-drops 60 120 --lr-drop-rate=0.1 --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=0 --post-epochs=160 --gpu=0 --result-dir=/mnt/fs4/htanaka/SynFlow/Results --expid=cifar10_lottery_vgg11_bn_${val}_comp_ratio_${d}_run${seed} --seed=$seed --dataset=cifar10 --model-class=lottery --model=vgg11-bn --pruner=$val --prune-epochs=100 --compression=$d
            else
                CUDA_VISIBLE_DEVICES=0 python3 main.py --experiment=singleshot --optimizer=momentum --lr=0.1 --lr-drops 60 120 --lr-drop-rate=0.1 --train-batch-size=128 --weight-decay=1e-4 --pre-epochs=0 --post-epochs=160 --gpu=0 --result-dir=/mnt/fs4/htanaka/SynFlow/Results --expid=cifar10_lottery_vgg11_bn_${val}_comp_ratio_${d}_run${seed} --seed=$seed --dataset=cifar10 --model-class=lottery --model=vgg11-bn --prune-train-mode=True --pruner=$val --prune-epochs=1 --compression=$d
            fi
        done
    done
done
